services:
  postgres:
    image: postgres:13
    container_name: auth_postgres
    expose:
      - '5432'
    ports:
      - "5432:5432"
    env_file:
      - ./.env
      
  redis:
    image: redis:6.2.6
    container_name: auth_redis
    expose:
      - "6379"
    command:
      - redis-server

  main:
    init: true
    container_name: auth_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT_APP=5000
      - WORKERS=1
    env_file:
      - ./.env
    expose:
      - "5000"
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:1.19.2
    container_name: auth_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - main
